### ISSUE TITLE
[question] Difference between mpv-winbuild and mpv-win64

### ISSUE THREAD

**Issue by sergeevabc** [eko5624/mpv-winbuild#4]
Dear @eko5624, I am confused,
could you be so kind to explain the difference between these repos of yours?

* [mpv-winbuild](https://github.com/eko5624/mpv-winbuild)
* [mpv-win64](https://github.com/eko5624/mpv-win64)

Both contain recent versions of MPV that are compatible with Windows 7…

**Comment by eko5624** [comment]
The first one is cross-compiled on archlinux. And the second one is compiled in msys2 environment on Windows platform. And the toolchain is different. I suggest you use gcc-mcf build both.

**Comment by eko5624** [comment]
My mpv-winbuild repo with clang build also supports Windows 7 for now.

**Comment by sergeevabc** [comment]
@eko5624, and what's the difference between Clang and GCC with the MCF thread?

**Comment by eko5624** [comment]
Check https://github.com/msys2/MINGW-packages/discussions/13259

mcfgthread should be able to bring some [performance improvements](https://github.com/lhmouse/mcfgthread#benchmarking) .
