### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by greenozon** [eko5624/mpv-winbuild#6]
hi!
there is a single-liner in the readme regarding how to build the  repo
it says using Actions
So I"ve closed your repo (thanks for your work!) and tried to build the w7 branch, but it shows lots of fails...
https://github.com/greenozon/mpv-winbuild/actions/runs/10830530709/job/30050498243#step:7:40

do you have some secret steps or precedence in order to reach the green light?

**Comment by eko5624** [comment]
step 1.  Set your repository secrets:
![1](https://github.com/user-attachments/assets/c155745b-ca39-4e65-81b8-52eeb026ea81)

step 2.  Run cache-gcc-win32.yml
![2](https://github.com/user-attachments/assets/ade0ae9d-d8a6-40d7-a1d6-765988cd4568)

step 3.  Run build-mpv.yml
![3](https://github.com/user-attachments/assets/80064803-6e8a-445f-8c7c-eb6ffb6b5072)

**Comment by greenozon** [comment]
thanks!
sorry for this silly question but what value should I put into the `BOT` secret?

**Comment by eko5624** [comment]
![4](https://github.com/user-attachments/assets/2a4f9543-7dcf-4fb4-b7fa-e097974a0ff4)

**Comment by greenozon** [comment]
Thank you!

I set up the BOT token now

and moved to run the Actions as in your order
but hit another fail on the 1st one:

https://github.com/greenozon/mpv-winbuild/actions/runs/10834033420/job/30062227736

![image](https://github.com/user-attachments/assets/83f41abc-6357-49c6-97cd-54e6cd8408dc)


is it something known or I'm the pioneer? :)

**Comment by eko5624** [comment]
Path issue. For win7, you should use this rust toolchain: https://github.com/eko5624/toolchain/releases/download/toolchain/rust-for-win7-1.77.2.7z

**Comment by eko5624** [comment]
By the way, you should run toolchain cache actions on main branch, not w7 branch.

**Comment by greenozon** [comment]
thanks
1st green light in the tunnel! crossing fingers

![image](https://github.com/user-attachments/assets/32b50777-c69b-4d24-a383-e1e34f0345b5)

**Comment by greenozon** [comment]
what compiler should I choose in the build all-in-one MPV GH Action?
looks like clang is not OK?

![image](https://github.com/user-attachments/assets/f830f579-5bc6-44d3-80fe-7ecc6a9df032)

**Comment by greenozon** [comment]
Thank you for support!
gcc did the magic

![image](https://github.com/user-attachments/assets/81f5c759-2eac-4ec3-ae38-13faf2bcdf59)


never seen such a complicated build! dozens of libs :)
wow

**Comment by eko5624** [comment]
GCC toolchain support win7 build, clang only support win10 build for now.
