### ISSUE TITLE
Windows7 support

### ISSUE THREAD

**Issue by greenozon** [eko5624/mpv-winbuild#7]
Hi! does your fork support run on Win7 x64 SP1 ESU?
right now I've tried  mpv-x86_64-20240901-git-7c672e3.7z
and it show the error

```
---------------------------
mpv.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000005). Click OK to close the application. 
---------------------------
OK   
---------------------------

```

**Comment by eko5624** [comment]
mpv drop win7 support officially, so there's nothing we can do.

**Comment by greenozon** [comment]
Could you hint the latest build for W7?
I tried to search but ... looks like it got expired/etc
anyway, thanks, feel free to close the ticket

**Comment by eko5624** [comment]
You can try my build before 2024-05-20.

**Comment by greenozon** [comment]
Thanks! will give it a try shortly
btw, you have very vivid memory if you know it by heart! :)

**Comment by greenozon** [comment]
I really try hard like 10 or so builds before 2024-05-20 but ... same  error
thats is very unfrotunate

one build though thows this instead:
```
---------------------------
mpv.exe - Entry Point Not Found
---------------------------
The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------
```

**Comment by eko5624** [comment]
I did some tests, this is the last build working on win7.
https://github.com/eko5624/mpv-win64/releases/tag/2024-04-29

**Comment by greenozon** [comment]
Great news, 
it does work on WIndows7!
thank you very much for help and communication!

**Comment by eko5624** [comment]
@greenozon 
I did some research, only latest libdovi doens't support Windows 7. Because rust toolchain no longer support Win7 since 1.77.2. I rollback to https://github.com/quietvoid/dovi_tool/releases/tag/libdovi-3.3.0.
The rust toolchain, I rollback to 1.77.2-x86_64-unknown-linux-gnu, and cargo-c rollback to "0.9.31+cargo-0.78"

And about MPV. MPV add Media Control support since https://github.com/mpv-player/mpv/commit/6a43514097b709eb5a70b33f25b3ad3db92e7bac, but Win7 not support it. So I remove cppwinrt from toolchain. 
Bingo! MPV works on Win7 again.
You can try this build: https://github.com/eko5624/mpv-winbuild/releases/tag/2024-09-12

**Comment by greenozon** [comment]
Amazing stuff! kudos!

![image](https://github.com/user-attachments/assets/60b9d09e-a659-4c9b-a51b-ab5836e755c1)


Could I ask you to add some description that this build is Win7 compatible (in download or Release sectino) so that anyone in the future will easily find this build and have a luxury to play H264/265/266/VVC/AV1/etc  medias!

**Comment by greenozon** [comment]
Or maybe make some special note in the repo README file that will point to that W7 compatible build?
Thanks once again for such a great stuff!

**Comment by eko5624** [comment]
> Could I ask you to add some description that this build is Win7 compatible (in download or Release sectino) so that anyone in the future will easily find this build and have a luxury to play H264/265/266/VVC/AV1/etc medias!

Current build can play H264/265/AV1. H266/VVC decoder will be added in the future.

> Or maybe make some special note in the repo README file that will point to that W7 compatible build?

You can fork my repo(w7 branch), and build for W7 yourself.
 https://github.com/eko5624/mpv-winbuild/tree/w7

**Comment by greenozon** [comment]
OK! will do
I do understand it kind of burden to keep old trash in the cutting edge bits :)

its strange, but I was testing my small home zoo of media and I bet it has a H266, will check once again and get back

**Comment by greenozon** [comment]
example of playing VVC codec media:

![image](https://github.com/user-attachments/assets/bdedef21-b44c-417e-8883-767eb424f098)

**Comment by eko5624** [comment]
Can you upload a sample video with H.266/VCC encode, then I will try to add H.266/VCC dec.

**Comment by greenozon** [comment]
I"m using samples from here:  https://www.elecard.com/videos

**Comment by eko5624** [comment]
> Could I ask you to add some description that this build is Win7 compatible (in download or Release sectino) so that anyone in the future will easily find this build and have a luxury to play H264/265/266/VVC/AV1/etc medias!

Done!
![5](https://github.com/user-attachments/assets/a329b302-6d73-4a5b-9576-3288637f1f39)

Try this build: https://github.com/eko5624/mpv-winbuild/releases/download/2024-09-12/static-mpv-x86_64.7z

**Comment by greenozon** [comment]
this build plays all my zoo media, except one:

BBBmkvVVCsample.mkv

but I don't remeber where I got it from from
it should be BigBugsBunny using VVC1 coded but in mkv container

it's just 400 KB in size

intereesting thing is that MPC also can't play it:

![image](https://github.com/user-attachments/assets/ffcd8cde-df48-4248-8f2a-302b5a059689)

**Comment by eko5624** [comment]
@greenozon This is the last build for win7.
https://github.com/eko5624/mpv-winbuild/releases/download/2024-10-07/static-mpv-x86_64.7z

Since https://github.com/mpv-player/mpv/commit/1a3e3a0c98d41899481908de6362bb0fafc7cf8f , Win7 be dropped.
Luckily, I found another solution here.
https://github.com/i486/VxKex

**Comment by sergeevabc** [comment]
https://github.com/eko5624/mpv-winbuild/releases/tag/2024-10-07 says it's the last build for Windows 7, but on my end it throws an error as follows

```--------------------------
mpv.exe - System Error
---------------------------
The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

The one that actually works is https://github.com/eko5624/mpv-win64/releases/tag/2024-04-29

``` console
$ mpv.com --version
mpv v0.38.0-97-gb68c742b27 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 29 2024 00:36:49
libplacebo version: v7.349.0 (v6.338.0-127-g6aa96c72)
FFmpeg version: N-115021-g651f3aa7f9
FFmpeg library versions:
   libavutil       59.16.101
   libavcodec      61.5.103
   libavformat     61.3.103
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```

**Comment by sergeevabc** [comment]
The one that actually works is https://github.com/eko5624/mpv-win64/releases/tag/2024-04-29

``` console
$ mpv.com --version
mpv v0.38.0-97-gb68c742b27 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 29 2024 00:36:49
libplacebo version: v7.349.0 (v6.338.0-127-g6aa96c72)
FFmpeg version: N-115021-g651f3aa7f9
FFmpeg library versions:
   libavutil       59.16.101
   libavcodec      61.5.103
   libavformat     61.3.103
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```

**Comment by eko5624** [comment]
It works on my win7 PC. 
![71a7bb18cbb28de515c47ed9dd608659](https://github.com/user-attachments/assets/d8d4087b-8134-414c-a438-1a5f05d85b22)

Did you install [vc_redist.x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)?

**Comment by sergeevabc** [comment]
> Did you install [vc_redist.x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)?

Yes, I did.

Library `api-ms-win-core-path-l1-1-0.dll` does not exist under Windows 7.
And even putting a [hacked one][1] (or [another][2]) into MPV folder does not help.

[1]: https://github.com/nalexandru/api-ms-win-core-path-HACK/
[2]: https://github.com/A2uria/api-ms-win-core-path-l1-1-0

**Comment by eko5624** [comment]
Don't know why you need `api-ms-win-core-path-l1-1-0.dll`, not on my end. Try to put it in  `C:\Windows\System32`?

**Comment by sergeevabc** [comment]
This problem is [not unique][1]. Some component here uses newer [WinAPI function][4] which is [not supported][3] under Windows 7. Sometimes developers manage to [replace that call][2] or change the compilation target to include older OSes.

[1]: https://github.com/cwansart/sha256sum.exe/issues/5
[2]: https://github.com/dotnet/installer/pull/13646
[3]: https://stackoverflow.com/questions/70868766/dependencies-on-vcruntime140-dll-and-api-ms-win-core-path-l1-1-0-dll
[4]: https://stackoverflow.com/a/71267660
